spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa: # ORM
    show-sql: true
#    database: mysql
#
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
# ??! ?? ????? ?? ??? ??
#database? database-pplatform? JPA? ????? ?????? ?? ??? mariaDB? ?? ??? ????? ?? ?? ?? ?? ?
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
jwt :
  secret : {SECRET_KEY}

  logging:
    level:
      org:
        springframework: security = DEBUG